license="GNU General Public License v3.0"
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/Additional-Bars/issues" #optional

[[mods]] #mandatory
modId="additionalbars" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Additional Bars" #mandatory
displayURL="https://github.com/CodenameRevy/Additional-Bars" #optional
logoFile="logo.png" #optional
credits='''
CodenameRevy (Mod Developer),
ruchom4u (Spanish Translations),
fantasyair18 (Chinese Traditional (Taiwan) Translations),
TheDirectorX, BardinTheDwarf (Russian Translations),
Zijuna (German Translations),
justmonika (Simple Chinese Translations),
mindy15963 (Korean Translations),
WadeMason''' #optional
authors="CodenameRevy" #optional
description='''
This mod adds additional bars to the game that go along with Iron Bars!
'''

[[dependencies.additionalbars]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.additionalbars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
